[project]
dependencies = ["selenium>=4.39.0"]
description = "싱싱한 NCBP(네이버카페 백업 프로그램)"
name = "ShingshingBP"
readme = "README.md"
requires-python = ">=3.13"
version = "0.4"

[dependency-groups]
dev = ["jupyter-console>=6.6.3", "jupyter-core>=5.9.1"]
